#!/usr/bin/env -S fish --no-config
if test $argv[1] != upscale
    set -l INPUTIMG $argv
    set -l EXTENSION (path extension $INPUTIMG)
    set -l OUTPREP (path change-extension '' $INPUTIMG)
    rembg i $INPUTIMG {$OUTPREP}_BGless{$EXTENSION}
else
    set -l INPUTIMG $argv[2]
    set -l EXTENSION (path extension $INPUTIMG)
    set -l OUTPREP (path change-extension '' $INPUTIMG)
    upscayl-cli -n upscayl-standard-4x -i $INPUTIMG -o {$OUTPREP}_upscald{$EXTENSION}
end
return
